[project]
name = "book-crawler"
version = "0.1.0"
description = "小说爬虫项目，支持多个小说网站的搜索和章节信息获取"
requires-python = ">=3.13"
dependencies = [
    "scrapy>=2.11.0",
    "requests>=2.31.0",
    "lxml>=4.9.0"
]
[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true